apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-test-ns
  namespace: test-ns
spec:
  hard:
    requests.cpu: '1'
    requests.memory: 1Gi
    limits.cpu: '2'
    limits.memory: 2Gi
    pods: '3'
    persistentvolumeclaims: '5'
    requests.storage: 5Gi
    count/deployment.apps: 2
